### ISSUE TITLE
Helper function opens in new tab

### ISSUE THREAD

**Issue by stombeur** [michael79bxl/open-eid#2]
is there a way to rewrite open-eid.js to use the current open tab? or maybe use a hidden iframe?

**Comment by michael79bxl** [comment]
Nope since it is a native app. 

It may possible by using each browser api to look for the tab or even better the iframe as you proposed. 

That would require a lot of coding and dependies. That would be for future releases. 

Anyway ain't no problem using the app + the extension.

**Comment by michael79bxl** [comment]
I second thought and maybe the helper can simply open the browser in a hidden state.
I will test this and get back to you.

**Comment by stombeur** [comment]
hi michael, if you can point me in the right direction i can do the work if you want. You are right that the extension does this very nicely.

I am planning to use this on a few unattented pc's and I would like to reduce the number of components I need to install to as few as possible, so not having to install the extension would be nice.

anything I can do to help just tell me

**Comment by stombeur** [comment]
hi again, I tried making it work with --headless (i think you already tried this as well, looking at the source code), but can't get it to work. Even tried --user-data-dir and --profile-directory options. I think there is something in headless mode that makes it write to localstorage differently, so even specifying the correct profile folder does not make it write to the correct location. (I only tried with chrome on mac, maybe I'll try later with chrome on win as well)
I also tried out --no-sandbox, but no change
I think this issue https://github.com/GoogleChrome/puppeteer/issues/1268 is what plays
I will try cookies instead of localstorage tonight

**Comment by michael79bxl** [comment]
This is indeed a bug. Google Chrome App argument was ignored. I will fix
this in the next few days. I'm still looking for other browsers solutions.
For your auto install process, I will also add a silent flag for
installation. Regards. Michael

Le mar. 7 mai 2019 à 11:19, Stephane Tombeur <notifications@github.com> a
écrit :

**Comment by michael79bxl** [comment]
This is indeed a bug. Google Chrome App argument was ignored. I will fix
this in the next few days. I'm still looking for other browsers solutions.
For your auto install process, I will also add a silent flag for
installation. Regards. Michael

**Comment by michael79bxl** [comment]
The helper function has been updated. Under Google Chrome, the default is now to use "#Google Chrome App" which opens a popup instead of a new tab. This week, I will release v0.2 with open-eid-sign: URL scheme.

**Comment by michael79bxl** [comment]
What OS are you working on?

**Comment by stombeur** [comment]
mac os 10.13

**Comment by michael79bxl** [comment]
Release 0.1.4 should work (similar os & browser here)
Also take a look at https://e-id.eu.org/samples/viewer.html
